language: go
go:
    - 1.x
notificaitons:
  email:
    recipients: dave@brophy.uk
    on_failure: always
install:
  - go get -u github.com/dave/courtney
  - go get -t -v ./...
script:
  - courtney -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
